name: Test Artifacts
on:
  push:
    branches:
      - main
      - develop
jobs:
  artifacts:
    name: Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: environment-state-files
          path: artifacts/

      - name: Check for downloaded artifacts
        run: |
          ls -a artifacts
          cat artifacts/a.txt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Make a file
        run: |
          echo hello > artifacts/a.txt

      - name: Upload state files
        uses: actions/upload-artifact@v3
        with:
          name: environment-state-files
          path: artifacts/*.txt
          if-no-files-found: warn

      - name: Upload state files2
        uses: actions/upload-artifact@v3
        with:
          name: environment-state-files2
          path: artifacts/*
          if-no-files-found: warn
