name: Test Artifacts
on:
  push:
    branches:
      - main
      - develop
jobs:
  artifacts:
    name: Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upload state files
        uses: actions/upload-artifact@v3
        with:
          name: environment-state-files
          path: files
          if-no-files-found: warn
