name: Test Artifacts
on:
  push:
    branches:
      - main
      - develop
jobs:
  artifacts:
    name: Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install aws cli
        run: |
          python3 -m pip install --user awscli

      - name: Download artifact
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp s3://agnone/a.txt artifacts/a.txt

      - name: Edit the artifact file
        run: |
          date >> artifacts/a.txt

      - name: Upload artifact
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp artifacts/a.txt s3://agnone/a.txt
